//  e.g => if user selected mobile then all the necessary details of mobile.

export const mapCategoriesToOptions = {
  mobile: [
    "ram_storage",
    "rom_storage",
    "operating_system",
    "rear_camera",
    "front_camera",
    "screen_size",
    "cpu",
  ],
  laptop: [
    "ram_storage",
    "rom_storage",
    "operating_system",
    "screen_size",
    "cpu",
  ],
  watch: [
    "diameter",
    "is_digital",
    "is_calling_available",
    "have_fitness_tracker",
  ],
  monitor: ["screen_size"],
  keyboard: [],
  mouse: ["is_wireless"],
  headphone: ["is_wireless"],
  electronics: [],
  common: [
    "brand_name",
    "model_name",
    "product_color",
    "set_price",
    "original_price",
    "title",
    "desc",
    "usage_time",
    "bid_start_time",
    "product_appeal",
    "bid_time",
  ],
};

export const mapCategoriesToInput = {
  brand_name: "text",
  model_name: "text",
  ram_storage: "text",
  rom_storage: "text",
  operating_system: "text",
  rear_camera: "text",
  front_camera: "text",
  product_color: "text",
  screen_size: "text",
  cpu: "text",
  set_price: "number",
  original_price: "number",
  title: "text",
  desc: "text",
  usage_time: "date",
  bid_start_time: "time",
  product_appeal: "text",
  bid_time: "number",
  diameter: "number",
  is_digital: "text",
  is_calling_available: "number",
  have_fitness_tracker: "number",
  is_wireless: "text",
};
